# Generated by Django 5.0 on 2023-12-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('departmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('departmentname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employeeid', models.IntegerField(primary_key=True, serialize=False)),
                ('employeename', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('dateofjoining', models.DateField()),
                ('photo', models.CharField(max_length=150)),
            ],
        ),
    ]
