# Generated by Django 5.0 on 2023-12-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
